language: csharp
sudo: false
env:
  global:
    - CONFIGURATION="Release"
mono:
  - 3.12.0
  - 3.10.0
solution: Optic.sln
install:
  - nuget install Persimmon.Console -Pre -OutputDirectory packages -ExcludeVersion
script:
  - xbuild ./Optic.sln /p:Configuration=${CONFIGURATION}
  - mono --runtime=v4.0 ./packages/Persimmon.Console/tools/Persimmon.Console.exe --parallel ./Optic.Tests/bin/${CONFIGURATION}/Optic.Tests.dll

